package com.codereviewer.nodes;

import com.codereviewer.state.CodeReviewState;
import com.codereviewer.tools.GitHubClient;
import org.bsc.langgraph4j.action.NodeAction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Node 4 — Renders the merged findings into a structured GitHub markdown review
 * and posts it to the PR via the GitHub API.
 *
 * Output format mirrors what a senior engineer would write:
 * sections grouped by severity, each with file + line reference + fix.
 */
@Component
public class CommentBuilderNode implements NodeAction<CodeReviewState> {

    private static final Logger log = LoggerFactory.getLogger(CommentBuilderNode.class);

    private static final Pattern FINDING_BLOCK = Pattern.compile(
        "SEVERITY:\\s*(.+?)\\nFILE:\\s*(.+?)\\nLINE:\\s*(.+?)\\nCATEGORY:\\s*(.+?)\\nAGENT:\\s*(.+?)\\nISSUE:\\s*(.+?)\\nFIX:\\s*(.+?)(?=\\n---|$)",
        Pattern.DOTALL
    );

    @Value("${app.review.post-to-github:true}")
    private boolean postToGitHub;

    private final GitHubClient gitHubClient;

    public CommentBuilderNode(GitHubClient gitHubClient) {
        this.gitHubClient = gitHubClient;
    }

    @Override
    public Map<String, Object> apply(CodeReviewState state) throws Exception {
        String mergedFindings = state.mergedFindings().orElse("NO_ISSUES_FOUND");
        String owner          = state.owner().orElseThrow();
        String repo           = state.repo().orElseThrow();
        int    prNumber       = state.prNumber().orElseThrow();
        String prTitle        = state.prTitle().orElse("PR #" + prNumber);

        log.info("CommentBuilderNode: rendering review for {}/{}#{}", owner, repo, prNumber);

        String review = renderMarkdown(prTitle, prNumber, mergedFindings);

        if (postToGitHub) {
            log.info("CommentBuilderNode: posting review to GitHub PR #{}", prNumber);
            gitHubClient.postReview(owner, repo, prNumber, review);
            log.info("CommentBuilderNode: review posted successfully");
        } else {
            log.info("CommentBuilderNode: dry-run mode — review NOT posted to GitHub");
            log.info("=== RENDERED REVIEW ===\n{}", review);
        }

        return Map.of(
            "renderedReview", review,
            "status", "complete"
        );
    }

    // ── Markdown rendering ────────────────────────────────────────────────────

    private String renderMarkdown(String prTitle, int prNumber, String mergedFindings) {
        if ("NO_ISSUES_FOUND".equals(mergedFindings.trim())) {
            return noIssuesReview(prTitle);
        }

        List<Finding> findings = parseFindings(mergedFindings);
        if (findings.isEmpty()) {
            return noIssuesReview(prTitle);
        }

        long critical = findings.stream().filter(f -> "CRITICAL".equals(f.severity())).count();
        long major    = findings.stream().filter(f -> "MAJOR".equals(f.severity())).count();
        long minor    = findings.stream().filter(f -> "MINOR".equals(f.severity())).count();

        StringBuilder sb = new StringBuilder();
        sb.append("## 🤖 Autonomous Code Review\n\n");
        sb.append("> Generated by **Code Review Agent** (LangGraph4J · Groq llama3-70b · Spring AI)  \n");
        sb.append("> Reviewed: `").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))).append(" UTC`\n\n");
        sb.append("---\n\n");

        // Summary table
        sb.append("### Summary\n\n");
        sb.append("| Severity | Count |\n");
        sb.append("|----------|-------|\n");
        if (critical > 0) sb.append("| 🔴 Critical | ").append(critical).append(" |\n");
        if (major > 0)    sb.append("| 🟡 Major    | ").append(major).append(" |\n");
        if (minor > 0)    sb.append("| 🔵 Minor    | ").append(minor).append(" |\n");
        sb.append("| **Total** | **").append(findings.size()).append("** |\n\n");
        sb.append("---\n\n");

        // Findings grouped by severity
        appendFindingsSection(sb, "🔴 Critical Issues", "CRITICAL", findings);
        appendFindingsSection(sb, "🟡 Major Issues",    "MAJOR",    findings);
        appendFindingsSection(sb, "🔵 Minor Issues",    "MINOR",    findings);

        sb.append("---\n\n");
        sb.append("_This review was generated automatically. Please verify findings before acting. ");
        sb.append("False positives may occur. Human judgment is always the final authority._\n");

        return sb.toString();
    }

    private void appendFindingsSection(StringBuilder sb, String heading, String severity, List<Finding> findings) {
        List<Finding> filtered = findings.stream()
            .filter(f -> severity.equals(f.severity()))
            .toList();
        if (filtered.isEmpty()) return;

        sb.append("### ").append(heading).append("\n\n");
        for (int i = 0; i < filtered.size(); i++) {
            Finding f = filtered.get(i);
            sb.append("<details open>\n");
            sb.append("<summary><strong>[").append(f.category()).append("]</strong> ");
            sb.append("`").append(f.file()).append("` line ").append(f.line());
            sb.append(" <em>(").append(f.agent()).append(" Agent)</em></summary>\n\n");
            sb.append("**Issue:** ").append(f.issue().trim()).append("\n\n");
            sb.append("**Fix:** ").append(f.fix().trim()).append("\n\n");
            sb.append("</details>\n\n");
        }
    }

    private String noIssuesReview(String prTitle) {
        return """
            ## 🤖 Autonomous Code Review
            
            > Generated by **Code Review Agent** (LangGraph4J · Groq llama3-70b · Spring AI)
            
            ### ✅ No issues found
            
            The Security, Logic, and Style agents reviewed this PR and found no issues.
            
            _This review was generated automatically._
            """;
    }

    // ── Finding parser ────────────────────────────────────────────────────────

    private List<Finding> parseFindings(String text) {
        List<Finding> findings = new ArrayList<>();
        Matcher m = FINDING_BLOCK.matcher(text);
        while (m.find()) {
            findings.add(new Finding(
                m.group(1).trim(),
                m.group(2).trim(),
                m.group(3).trim(),
                m.group(4).trim(),
                m.group(5).trim(),
                m.group(6).trim(),
                m.group(7).trim()
            ));
        }
        return findings;
    }

    private record Finding(
        String severity,
        String file,
        String line,
        String category,
        String agent,
        String issue,
        String fix
    ) {}
}
